// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqCekV7UF2o7IhATAkw8LJPDPJKjUGtCk',
    appId: '1:453244612455:web:e2716f130c9b920be5c9c2',
    messagingSenderId: '453244612455',
    projectId: 'mynotes-karl',
    authDomain: 'mynotes-karl.firebaseapp.com',
    storageBucket: 'mynotes-karl.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeUdrIgtOC_EMPXdHKnjVd5NMGW0tQYhw',
    appId: '1:453244612455:android:3e6c11b17f934753e5c9c2',
    messagingSenderId: '453244612455',
    projectId: 'mynotes-karl',
    storageBucket: 'mynotes-karl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMKodb92b605JJmDcWZZ8DagvydR-F60U',
    appId: '1:453244612455:ios:09133aacc17aa4e9e5c9c2',
    messagingSenderId: '453244612455',
    projectId: 'mynotes-karl',
    storageBucket: 'mynotes-karl.firebasestorage.app',
    iosBundleId: 'com.learnflutter.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMKodb92b605JJmDcWZZ8DagvydR-F60U',
    appId: '1:453244612455:ios:09133aacc17aa4e9e5c9c2',
    messagingSenderId: '453244612455',
    projectId: 'mynotes-karl',
    storageBucket: 'mynotes-karl.firebasestorage.app',
    iosBundleId: 'com.learnflutter.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqCekV7UF2o7IhATAkw8LJPDPJKjUGtCk',
    appId: '1:453244612455:web:aab22ea1f6749ab1e5c9c2',
    messagingSenderId: '453244612455',
    projectId: 'mynotes-karl',
    authDomain: 'mynotes-karl.firebaseapp.com',
    storageBucket: 'mynotes-karl.firebasestorage.app',
  );
}
